name: Orange HRM Automation Suite

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      ORANGEHRM_USER: ${{ secrets.ORANGEHRM_USER }}
      ORANGEHRM_PASSWORD: ${{ secrets.ORANGEHRM_PASSWORD }}
      EMAIL: ${{secrets.EMAIL}}
      EMAIL_PASS: ${{secrets.EMAIL_PASS}}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: run the automation framework
      run: mvn clean test -Dsuite=testng.xml

    - name: upload extent reports
      uses: actions/upload-artifact@v4.6.2
      with:
        name: extent-report
        path: target/reports/extent-report.html
